# Generated by Django 4.0.2 on 2022-02-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photo /%Y/%m/%d/')),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(choices=[('#000000', 'Noir'), ('#ffffff', 'Blanc'), ('#ff0000', 'Rouge'), ('#ffff00', 'Jaune'), ('#808080', 'Gris')], default='#ffffff', max_length=13)),
                ('stock', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
